version: '3.7'
services:
  postgres:
    image: postgres:9.6
    ports:
      - 9003:5432
    environment:
      POSTGRES_USER: rxgoodness
      POSTGRES_PASSWORD: 287693@Ata
      POSTGRES_DB: rxgoodness2
    logging:
            options:
                max-size: 10m
                max-file: "3"
    networks:
      - rxgoodness
  db:
    image: dpage/pgadmin4
    ports:
      - 5435:5432
    logging:
            options:
                max-size: 10m
                max-file: "3"
    environment:
      - PGADMIN_DEFAULT_EMAIL=adedokuntoyyib@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=287693@Ata
    networks:
      - rxgoodness
networks:
  rxgoodness: